from pydantic import BaseModel, Field
from settings import settings
from qdrant_client import QdrantClient, models
from logging_config import configure_logging, get_logger

COLLECTION = settings.QDRANT_PURCHASE_ORDERS
qdrant = QdrantClient(url=settings.QDRANT_URL)
configure_logging()
logger = get_logger(__name__)


class PurchaseOrder(BaseModel):
    po_id: str = Field(min_length=1, description="Purchas order generated by Customer")
    supplier_id: str = Field(min_length=1, description="Supplier provided Item name/id")
    quantity: int = Field(
        gt=0, strict=True, description="No of Item to be purchased by customer"
    )
    unit_price: float = Field(gt=0, allow_inf_nan=False, description="")
    currency: str = Field(min_length=1, description="INR, USD")


def insert_purchase_order():

    if not qdrant.collection_exists(COLLECTION):
        logger.info("Create Database table ")
        qdrant.create_collection(
            collection_name=COLLECTION,
        )

    point_id = 104
    purchase_order = PurchaseOrder(
        po_id="PO-104",
        supplier_id="SUP-01",
        quantity=100,
        unit_price=500.00,
        currency="INR",
    )
    qdrant.upsert(
        collection_name=COLLECTION,
        wait=True,
        points=[
            models.PointStruct(
                id=point_id,
                vector={},
                payload=purchase_order.model_dump(mode="json"),
            )
        ],
    )


if __name__ == "__main__":
    insert_purchase_order()
