from pydantic import BaseModel, Field

class PurchaseOrder(BaseModel):
    po_id: str = Field(min_length=1, description="Purchas order generated by Customer")
    supplier_id: str = Field(min_length=1, description="Supplier provided Item name/id")
    quantity: int = Field(
        gt=0, strict=True, description="No of Item to be purchased by customer"
    )
    unit_price: float = Field(gt=0, allow_inf_nan=False, description="")
    currency: str = Field(min_length=1, description="INR, USD")
